# Generated by Django 2.2.6 on 2019-11-12 15:39

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0001_squashed_0021'),
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogAuthor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name=[])),
                ('reddit_url', models.URLField(blank=True, help_text='Reddit URL', null=True)),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL', null=True)),
                ('youtube_url', models.URLField(blank=True, help_text='Youtube URL', null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'Blog Author',
                'verbose_name_plural': 'Blog Authors',
            },
        ),
    ]
