# Generated by Django 2.2.6 on 2019-11-12 17:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20191112_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogdetailpage',
            name='quick_facts',
            field=wagtail.core.fields.RichTextField(blank=True, null=True),
        ),
    ]
