# Generated by Django 2.2.6 on 2019-11-12 18:35

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogdetailpage_quick_facts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', wagtail.core.blocks.StructBlock([]))], blank=True, null=True),
        ),
    ]
