# Generated by Django 2.2.6 on 2019-11-12 19:49

from django.db import migrations
import streams.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191112_1835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock())], blank=True, null=True),
        ),
    ]
