# Generated by Django 2.2.6 on 2019-11-13 18:40

from django.db import migrations
import streams.blocks
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20191112_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdetailpage',
            name='streams',
            field=wagtail.core.fields.StreamField([('full_richtext', streams.blocks.RichTextBlock()), ('large_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(max_length=250, null=True, required=False))])), ('small_image', wagtail.core.blocks.StructBlock([('image', wagtail.images.blocks.ImageChooserBlock(required=True)), ('caption', wagtail.core.blocks.CharBlock(max_length=250, null=True, required=False))]))], blank=True, null=True),
        ),
    ]
