# Generated by Django 2.2.6 on 2019-11-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_homepage_featured_blog_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='banner_title_1',
            new_name='banner_subtitle',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title_2',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title_3',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='banner_title_4',
        ),
    ]
