# Generated by Django 2.2.6 on 2019-11-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_auto_20191101_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Twitter URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='reddit_url',
            field=models.URLField(blank=True, help_text='Twitter URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Twitter URL', null=True),
        ),
    ]
