# Generated by Django 2.2.6 on 2019-11-10 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_auto_20191101_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutpage',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='reddit_url',
            field=models.URLField(blank=True, help_text='Reddit URL', null=True),
        ),
        migrations.AlterField(
            model_name='aboutpage',
            name='youtube_url',
            field=models.URLField(blank=True, help_text='Youtube URL', null=True),
        ),
    ]
